atualizar para utilizar versão 2019 do IRPF
felipewer/irpf pull request #3
Opened 2019-03-02 23:10 UTC by DouglasPioStudiare

Esse PR permite que seja utilizado a versão 2019 do programa de IRPF.

2019-03-05 14:32 UTC, felipewer requested changes

2019-03-05 14:32 UTC, felipewer commented on README.md
> +docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME:/home/irpf douglascpiocm4u/irpf
Podes reverter ao nome original do container aqui por gentileza?

2019-03-05 14:32 UTC, felipewer commented on README.md
> +    image: douglascpiocm4u/irpf
Reverter nome.

2019-03-05 14:32 UTC, felipewer commented on docker-compose.yml
> +    image: douglascpiocm4u/irpf
Reverter nome.

2019-03-22 13:29 UTC, DouglasPioStudiare commented on README.md
> +docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME:/home/irpf douglascpiocm4u/irpf
Claro... Foi mal a demora.

2019-03-22 13:55 UTC, DouglasPioStudiare commented
@felipewer, pelo que percebi o seu docker container ainda está com a versão 2018 do IRPF.

2019-03-22 14:00 UTC, DouglasPioStudiare commented
Dado que já foi feito um release com a versão 2019 do IRPF estou fechando esse PR.

2019-03-22 14:00 UTC, closed without merging